---
- name: Add pyenv environment vars to .bash_profile.
  blockinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bash_profile"
    content: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"

- name: Check installed python version.
  shell: |
    pyenv versions | grep -c {{ python_version }}
  register: python_version_exist
  changed_when: no

- name: Ensure to install python.
  shell: |
    source {{ lookup('env', 'HOME') }}/.bash_profile
    pyenv install {{ python_version }}
  when: not python_version_exist.stdout

- name: Ensure to install pip packages.
  pip:
    name: "{{ item }}"
  with_items: "{{ python_pip_packages }}"
