# Tap external Homebrew repositories.
#
# e.g.
# - homebrew/binary
homebrew_repositories:

# Managed Homebrew packages.
#
# e.g.
# - package_name
# or
# { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
#
# state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
# install_options: string or sequence (default: none)
homebrew_packages:
  - readline
  - openssl
  - ansible
  - git
  - git-flow
  - vim
  - pyenv

# Tap external Homebrew Cask repositories.
homebrew_cask_repositories:
  - caskroom/versions

# Managed Homebrew Cask packages.
#
# e.g.
# - package_name
# or
# { name: package_name, state: package_state }
#
# state choices: [present, absent, installed, uninstalled] (default: present)
homebrew_cask_packages:
  - atom
  - google-chrome
  - google-japanese-ime
  - karabiner
  - slack
  - vagrant
  - virtualbox
  - spectacle
  - clipy
  - appcleaner
  - dropbox

python_version: 3.6.2

python_pip_packages:
  - pytest
